import { read, save, consent, setConsent, dataFor, envelope, measure, api, refreshDebug, flush } from './measurement.js';
import { API_URL } from './config.js';
const root = new URL(document.body.dataset.root, location.href);
const route = document.body.dataset.route;
const main = document.querySelector('main');
const url = path => new URL(path, root).href;
const catalog = (await (await fetch(url('catalog.json'))).json()).products;
const money = amount => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(amount / 100);
let cart = read('nm-cart', []).filter(i => catalog.some(p => p.sku === i.sku && p.sizes.includes(i.size)) && Number.isInteger(i.quantity) && i.quantity > 0 && i.quantity <= 20);
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist() { save('nm-cart', cart); document.querySelector('#bag-count').textContent = cart.reduce((n, i) => n + i.quantity, 0); }
function toast(text) { const el = document.querySelector('#toast'); el.textContent = text; el.classList.add('visible'); setTimeout(() => el.classList.remove('visible'), 3000); }
function card(p) { return `<a class="product-card" href="${url('products/' + p.slug + '/')}" aria-label="${p.name}, ${money(p.price)}"><div class="product-image"><img src="${url(p.image)}" alt="Original illustration of ${p.name}" loading="lazy">${p.label ? `<span class="label">${p.label}</span>` : ''}<span class="quick">Explore ↗</span></div><div class="product-meta"><h3>${p.name}</h3><span>${money(p.price)}</span></div><p>${p.category} / ${p.sizes.length === 1 ? 'Everyday essentials' : 'Technical essentials'}</p></a>`; }
function membership() { return `<section class="membership" id="membership"><div><span class="eyebrow">THE NEXT CHAPTER</span><h2>A little more<br>in your movement.</h2><p>Early access. Shared momentum. A future membership designed around how you move.</p></div><form id="lead"><label for="interest">What moves you?</label><select id="interest" required><option value="">Choose your interest</option><option>Running</option><option>Training</option><option>Yoga</option><option>All movement</option></select><button>Register my interest ↗</button><small>Demo interest only. No contact details collected.</small><p id="lead-status" role="status"></p></form></section>`; }
function bindMembership() { document.querySelector('#lead')?.addEventListener('submit', e => { e.preventDefault(); const button = e.target.querySelector('button'); button.disabled = true; measure(envelope('lead_created'), { type: 'customer_action' }); document.querySelector('#lead-status').textContent = 'You’re on the movement list. Demo interest recorded.'; }); }
function home() {
  main.innerHTML = `<section class="hero"><div class="hero-copy"><span class="eyebrow">PERFORMANCE, WITHOUT THE NOISE / VOL. 01</span><h1>Small details.<br><em>Infinite</em><br>motion.</h1><p>Considered essentials for the miles, the moments,<br>and everything moving in between.</p><a class="button" href="${url('catalog/')}">Find your momentum <span>↗</span></a><div class="hero-caption">01 — BUILT TO MOVE WITH YOU</div></div><div class="hero-art"><div class="orbit"></div><img src="${url('assets/images/aero-run-shell.svg')}" alt="Aero Run Shell in sage, original Nano Motion illustration"><span class="hero-tag">AERO RUN SHELL<br>LIGHTER BY DESIGN</span><span class="vertical">NANO MOTION / FIELD NOTES 2026</span></div></section><div class="manifesto"><span>↗</span><p>Less friction.<br>More possibility.</p><p>We design for motion at every scale. Precision in every seam. Freedom in every stride. Nothing extra. Everything essential.</p></div><section class="section"><div class="section-heading"><div><span class="eyebrow">THE EVERYDAY ROTATION</span><h2>Made to go further.</h2></div><a href="${url('catalog/')}">Shop the collection ↗</a></div><div class="grid">${catalog.slice(0, 4).map(card).join('')}</div></section><section class="category-story"><span class="eyebrow">FIND YOUR ELEMENT</span><div>${['Running','Training','Yoga'].map((c, i) => `<a href="${url('catalog/?category=' + c)}"><small>0${i + 1}</small><h2>${c}</h2><span>Explore ↗</span></a>`).join('')}</div></section>${membership()}`;
  bindMembership();
}
function shop() {
  main.innerHTML = `<section class="catalog-head"><span class="eyebrow">THE NANO MOTION COLLECTION</span><h1>Your next<br><em>moving piece.</em></h1><p>Technical by nature. Essential by design.</p></section><section class="section"><div class="filters"><div role="group" aria-label="Product categories">${['All','Running','Training','Outerwear','Accessories','Yoga'].map(c => `<button data-category="${c}" aria-pressed="false">${c}</button>`).join('')}</div><label class="search">Search products<input type="search" id="search" placeholder="Find your essentials"></label></div><p id="result-count" role="status"></p><div class="grid" id="products"></div></section>`;
  let category = new URLSearchParams(location.search).get('category') || 'All';
  function draw() { const q = document.querySelector('#search').value.toLowerCase(); const found = catalog.filter(p => (category === 'All' || category === p.category) && (p.name + p.category).toLowerCase().includes(q)); document.querySelector('#products').innerHTML = found.map(card).join('') || '<p>No essentials found. Try another search.</p>'; document.querySelector('#result-count').textContent = `${found.length} essentials`; document.querySelectorAll('[data-category]').forEach(b => b.setAttribute('aria-pressed', b.dataset.category === category)); }
  document.querySelectorAll('[data-category]').forEach(b => b.onclick = () => { category = b.dataset.category; draw(); });
  document.querySelector('#search').oninput = draw; draw();
}
function product(p) {
  main.innerHTML = `<div class="breadcrumbs"><a href="${url('catalog/')}">Collection</a> / ${p.category} / ${p.name}</div><section class="product-detail"><div class="detail-image"><img src="${url(p.image)}" alt="Original illustration of ${p.name}"></div><div class="detail-copy"><span class="eyebrow">${p.category} / ${p.sku}</span><h1>${p.name}</h1><p class="price">${money(p.price)}</p><p>${p.description}</p><form id="add"><fieldset><legend>Select size</legend><div class="sizes">${p.sizes.map(s => `<label><input type="radio" name="size" value="${s}" required><span>${s}</span></label>`).join('')}</div></fieldset><button class="wide">Add to bag <span>↗</span></button></form><p class="detail-note">Mock storefront. No payments or shipping.</p><details open><summary>Made for movement</summary><ul>${p.features.map(f => `<li>${f}</li>`).join('')}</ul></details><details><summary>Material & care</summary><p>${p.material}. Cool wash. Air dry. These are fictional product specifications.</p></details></div></section><section class="section"><div class="section-heading"><h2>Keep the momentum.</h2></div><div class="grid">${catalog.filter(x => x.sku !== p.sku).slice(0,4).map(card).join('')}</div></section>`;
  measure(envelope('contents_viewed'), dataFor([{ sku:p.sku, size:p.sizes[0], quantity:1 }], catalog), { server:false });
  document.querySelector('#add').onsubmit = e => { e.preventDefault(); const size = new FormData(e.target).get('size'); const line = cart.find(i => i.sku === p.sku && i.size === size); if (line?.quantity >= 20) { toast('Maximum 20 per size.'); return; } if (line) line.quantity++; else cart.push({ sku:p.sku, size, quantity:1 }); persist(); const added = [{sku:p.sku,size,quantity:1}]; measure(envelope('items_added',added), dataFor(added,catalog)); toast(`${p.name} added to your bag`); };
}
function cartPage() {
  main.innerHTML = `<section class="section cart-section"><span class="eyebrow">YOUR EVERYDAY ROTATION</span><h1>Your bag<span class="accent">.</span></h1>${cart.length ? `<div class="cart-layout"><div>${cart.map((i, n) => {const p = catalog.find(p=>p.sku===i.sku);return `<article class="cart-line"><a href="${url('products/'+p.slug+'/')}"><img src="${url(p.image)}" alt="${p.name}"></a><div><h2>${p.name}</h2><p>Size ${escape(i.size)} / ${money(p.price)}</p><label>Quantity <input data-qty="${n}" type="number" min="1" max="20" value="${i.quantity}"></label><button class="text-button" data-remove="${n}">Remove ${p.name}</button></div><strong>${money(p.price*i.quantity)}</strong></article>`;}).join('')}</div><aside class="order-summary"><span class="eyebrow">ORDER SUMMARY</span><div><span>Subtotal</span><strong>${money(dataFor(cart,catalog).amount)}</strong></div><div><span>Demo shipping</span><span>Free</span></div><p>No charges, taxes, or shipping. This is a simulation.</p><a class="button wide" href="${url('checkout/')}">Mock checkout ↗</a><a href="${url('catalog/')}">Keep exploring</a></aside></div>` : `<p>Your next moving piece is waiting.</p><a class="button" href="${url('catalog/')}">Explore essentials ↗</a>`}</section>`;
  document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);persist();cartPage();});
  document.querySelectorAll('[data-qty]').forEach(input=>input.onchange=()=>{const n=Number(input.value);if(!Number.isInteger(n)||n<1||n>20){input.value=cart[Number(input.dataset.qty)].quantity;toast('Choose a quantity from 1 to 20.');return;}cart[Number(input.dataset.qty)].quantity=n;persist();cartPage();});
}
function checkout() {
  if (!cart.length) { main.innerHTML=`<section class="section"><h1>Your bag is empty.</h1><a class="button" href="${url('catalog/')}">Shop essentials ↗</a></section>`;return; }
  const started=envelope('checkout_started',cart); measure(started,dataFor(cart,catalog));
  let pending=read('nm-checkout-pending',null);
  if(pending && JSON.stringify(pending.items)!==JSON.stringify(cart)){pending=null;save('nm-checkout-pending',null);}
  main.innerHTML=`<section class="section checkout-section"><span class="eyebrow">ONE LAST STEP / SIMULATION</span><h1>Ready. Set.<br><em>Motion.</em></h1><div class="cart-layout"><form id="checkout-form"><div class="mock-notice"><strong>Mock checkout</strong><p>No payment, contact, or address information is requested. No physical order is placed.</p></div><label class="check"><input type="checkbox" required> I understand this is a demonstration order.</label><button class="wide" id="complete">Complete mock order ↗</button><p id="checkout-status" role="status"></p><button type="button" id="offline" class="secondary wide" hidden>Continue as local simulation</button></form><aside class="order-summary"><span class="eyebrow">YOUR ROTATION</span>${cart.map(i=>{const p=catalog.find(p=>p.sku===i.sku);return `<div><span>${p.name} × ${i.quantity}</span><strong>${money(p.price*i.quantity)}</strong></div>`;}).join('')}<div class="total"><span>Total</span><strong>${money(dataFor(cart,catalog).amount)}</strong></div><p>USD. Final demo total is validated by the API when available.</p></aside></div></section>`;
  let busy=false;
  const status=document.querySelector('#checkout-status');
  const button=document.querySelector('#complete');
  function complete(result,local=false){
    const order={...result,local,event:pending,created:Date.now(),browserSent:true};
    // Persist BEFORE emitting; refresh never repeats the order measurement.
    if(!save('nm-order',order)){status.textContent='Browser storage is unavailable. Enable storage before completing the demo.';busy=false;button.disabled=false;return;}
    if(local){measure(pending,result.data,{server:false,serverStatus:'unavailable; local simulation only',mode:'local simulation'});}
    else{measure(pending,result.data,{server:true,serverStatus:result.server_status,mode:result.mode});}
    cart=[];persist();save('nm-checkout-pending',null);location.href=url('confirmation/');
  }
  document.querySelector('#checkout-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;button.disabled=true;document.querySelector('#offline').hidden=true;status.textContent='Confirming your mock order…';
    pending ||= envelope('order_created',structuredClone(cart));
    if(!save('nm-checkout-pending',pending)){status.textContent='Enable browser storage to prevent duplicate demo orders.';busy=false;button.disabled=false;return;}
    try{const result=await api('/api/checkout',pending);complete(result);}
    catch(error){busy=false;button.disabled=false;const unavailable=!error.status||error.status>=500;status.textContent=unavailable?'The API is unavailable. Retry uses the same order ID. You may instead complete a clearly labeled local simulation; server measurement will remain unavailable.':'The API rejected this checkout. Review the cart and retry. No order has been confirmed.';document.querySelector('#offline').hidden=!unavailable;}
  };
  document.querySelector('#offline').onclick=()=>{if(busy||!pending)return;busy=true;button.disabled=true;complete({order_id:'LOCAL-'+pending.event_id.slice(0,8).toUpperCase(),event_id:pending.event_id,data:dataFor(pending.items,catalog)},true);};
}
function confirmation(){const order=read('nm-order',null);main.innerHTML=`<section class="confirmation section"><span class="confirmation-mark">↗</span><span class="eyebrow">${order?'MOMENTUM CONFIRMED':'NO COMPLETED ORDER'}</span><h1>${order?'Order complete.':'Your journey awaits.'}</h1>${order?`<p>Mock order <strong>${escape(order.order_id)}</strong></p><p>${money(order.data.amount)} USD · ${order.local?'Local simulation. API totals were not validated. No server event was delivered.':'Total validated against the server catalog. CAPI status at checkout: '+escape(order.server_status)+'.'}</p><p>This is a demonstration. No payment was collected and no items will ship.</p>`:''}<a class="button" href="${url('catalog/')}">Keep moving ↗</a></section>`;}
persist();
measure(envelope('page_viewed'),{type:'contents',contents:[{id:route||'home',name:document.title,content_type:'page'}]},{server:false});
if(!route)home();else if(route==='catalog')shop();else if(route==='cart')cartPage();else if(route==='checkout')checkout();else if(route==='confirmation')confirmation();else if(route.startsWith('products/'))product(catalog.find(p=>p.slug===route.split('/')[1]));
const consentPanel=document.querySelector('#consent');
consentPanel.hidden=localStorage.getItem('nm-consent')!==null;
document.querySelector('#privacy').onclick=()=>{consentPanel.hidden=false;document.querySelector('#accept').focus();};
document.querySelector('#accept').onclick=()=>{setConsent(true);consentPanel.hidden=true;toast('Measurement enabled for future actions.');};
document.querySelector('#decline').onclick=()=>{setConsent(false);consentPanel.hidden=true;toast('Optional measurement disabled.');};
refreshDebug();flush();
